site_name: 凯楽斯Kelesssの聖教天堂
site_url: https://www.kelesss.art
# 导航栏
nav:
  - 🏠首页:
    - 🏠首页: index.md
    - ⏲️最近更新: changelog.md
    - 🙋我要投稿！: commit.md
  - 🧪化学:
    - 化学-首页: "chem/index.md"
    - 物理化学:
      - 物理化学I笔记: "chem/physical/Physical_Chemistry_I.md"
      - 物理化学II笔记: "chem/physical/Physical Chemistry II.md"
      - 相与相图: "chem/physical/Phase_Diagram.md"
    - 理论化学:
      - 量子化学: "chem/theoretical/Quantum_Chemistry.md"
    - 竞赛晶体进阶十讲:
      - 0.前言: "chem/crystaljs/perface.md"
      - 1.宏观晶体与对称性: "chem/crystaljs/lecture1.md"
      - 2.晶体的表征、Bragg方程与系统消光: "chem/crystaljs/lecture2.md"
      - 3.堆积、多面体与晶体构造: "chem/crystaljs/lecture3.md"
      - 4.晶体与光电磁: "chem/crystaljs/lecture4.md"
      - 5.单质晶体: "chem/crystaljs/lecture5.md"
      - 6.八面体配位的晶体: "chem/crystaljs/lecture6.md"
      - 7.四面体配位的晶体: "chem/crystaljs/lecture7.md"
      - 8.体心立方: "chem/crystaljs/lecture8.md"
      - 9.分子晶体及其他: "chem/crystaljs/lecture9.md"
      - 10.晶体中的数学推导: "chem/crystaljs/lecture10.md"
  - 🔢数理:
    - 数理-首页: "maphy/index.md"
    - 数学基础:
      - 复变函数: "maphy/math/complex.md"
      - 数学物理方程: "maphy/math/PDE.md"
      - 微积分概要: "maphy/math/calculus.md"
      - 线性代数概要: "maphy/math/linear_algebra.md"
      - 概率统计概要: "maphy/math/probability.md"
    - 热学与热力学:
      - 统计热力学: "maphy/thermo_phys/Statistic_Thermodynamics.md"
      - 统热进阶专题: "maphy/thermo_phys/Statistic_Thermodynamics_2.md"
      - 近平衡态的热力学: "maphy/thermo_phys/Near_Eq.md"
      - 固体物理学: "maphy/thermo_phys/Solid_State_Physics.md"
      - 统计力学笔记: "maphy/thermo_phys/Statistic_Dynamics.md"
    - 量子物理:
      - 量子力学导论: "maphy/quant_phys/quant_phys_intro.md"
  - 🖥️计算机:
    - 计算机-首页: "cs/index.md"
    - 工具类应用:
      - Git基础: "cs/tools/git.md"
      - LaTeX physics宏包: "cs/tools/physics_pkg.md"
  - ☕杂货铺:
    - 杂货铺-首页: "lqbz/index.md"
    - 习作:
      - Genesis Organica: lqbz/writing/Genesis_Organica.md
    - 聖教相关:
      - 凯楽斯社会学教材: lqbz/holykelesss/social1.md
    - 弱智题大合集:
      - 失重的魅力1: lqbz/sbprob/sz1.md
      - 失重的魅力2: lqbz/sbprob/sz2.md
      - 失重的魅力3: lqbz/sbprob/sz3.md
      - 失重的魅力4: lqbz/sbprob/sz4.md
      - 失重的魅力5: lqbz/sbprob/sz5.md
      - 广义的热重分析: lqbz/sbprob/gyrz.md
      - “汉神杯”元素推断大赛: lqbz/sbprob/hsb.md
      - γChem 推断题选: lqbz/sbprob/ystd.md
      - 如金 Ruby Gold: lqbz/sbprob/rubygold.md
    - 锐评:
      - 锐评所有少女乐队番剧: lqbz/rp/band.md

  - 📚资料:
    - 资料-首页: refs/index.md
    - 化学相关书籍: 
      - 物理化学: refs/cbook/phys.md
      - 无机化学-热门🔥: refs/cbook/inorg.md
      - 无机化学-拓展💥: refs/cbook/inorg2.md
      - 有机化学-热门🔥: refs/cbook/org.md
      - 有机化学-拓展💥: refs/cbook/org2.md
      - 分析化学: refs/cbook/anal.md
      - 高分子物理和化学: refs/cbook/polymer.md
      - 理论与计算化学: refs/cbook/quant.md
      - 其他书籍: refs/cbook/other.md
    - 资源分享:
      - 化学相关: refs/software/chemsoft.md
      - 数学相关: refs/software/mathsoft.md
    - 化学竞赛题目:
      - PKU&THU春联/金秋营试题: refs/jsexam/pkuthu.md
  - 📓日记:
    - 日记-首页: blog/index.md

use_directory_urls: false

# material主题
theme:
  name: materialx
  custom_dir: overrides

  palette: 
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  language: zh
  favicon: imgs/logos/favicon.png
  logo: imgs/logos/favicon.png
  
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.expand
    - search suggest
    - search highlight
    - search share
    - navigation.footer
    - navigation.indexes
    - content.code.copy
    - navigation.top

plugins:
  - search:
      lang: 
        - zh
        - en
  - document-dates:
      recently-updated:
          limit: 6       
          exclude:
            - index.md
            - chem/index.md
            - maphy/index.md
            - cs/index.md
            - lqbz/index.md
            - refs/index.md
            - blog/*
  - optimize
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
  - meta
  - blog: 
      blog_toc: true
      archive_date_format: MMMM yyyy
  - changelog
  # - heti:
  #     disable_serve: false
  # - glightbox
  # - statistics
  - minify:
      minify_html: true

hooks:
  - hooks/toc.py
  - hooks/css_cache_bust.py

#页脚
extra:
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/SUPERkelesss
      - icon: bilibili-fill
        link: https://space.bilibili.com/334614292
      - icon: QQgroup
        link: https://qm.qq.com/q/YXattqg3Kg
      - icon: rednote
        link: https://www.xiaohongshu.com/user/profile/659dd609000000002001ca3b
      - icon: zhihu
        link: https://www.zhihu.com/people/ke-le-kelesss
copyright: Copyright © 2026 by <a href="https://github.com/SUPERkelesss" target="_blank">Kelesss</a> is licensed under CC BY-SA 4.0
#页眉
repo_url: https://github.com/SUPERkelesss/superkelesss.github.io.git
repo_name: superkelesss.github.io

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.superfences
  # 格式化排版
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
    

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#  - javascripts/katex.js
#  - https://unpkg.com/katex@0/dist/katex.min.js
#  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  # - https://3Dmol.org/build/3Dmol-min.js
  # - javascripts/vercel_statistics.js
  # - https://cdn.vercel.io/insights/script.js

extra_css:
#  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css
  - stylesheets/toc_extra.css
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
